// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/prod.proto

package prod

import "error"
import "github.com/jmoiron/sqlx"
import "net/http"
import "github.com/gin-gonic/gin"
import "github.com/gin-gonic/gin/binding"
import "github.com/op/go-logging"
import "golang.org/x/net/context"

// Reference imports to suppress errors if they are not otherwise used.

type ProductGrpcImp struct {
	Db  *sqlx.Db
	Log *logging.Logger
}

func (s *ProductGrpcImp) GetProd(c context.Context, in *ProdId) (*Prod, error) {
	var err error
	out := &Prod{}
	err = in.Validate()
	if err != nil {
		return out, err
	}
	err = s.Db.Get(out, "select * from prod where id = ?", in.Id)
	if err != nil {
		s.Log.Error(err.Error())
		return out, err
	}
	return out, nil
}

type ProductImp struct {
	ProductGrpcImp
}

func (s *ProductImp) GetProdHandler(c *gin.Context) {
	var prm *ProdId
	var err error
	err = c.ShouldBindWith(prm, binding.JSON)
	if err != nil {
		s.Log.Error(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"resp": err.Error()})
		return
	}
	if err = prm.Validate(); err != nil {
		s.Log.Error(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"resp": err.Error()})
		return
	}
	res, err := s.GetProd(context.Background(), prm)
	if err != nil {
		s.Log.Error(err.Error())
		c.JSON(http.StatusServiceUnavailable, gin.H{"resp": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"resp": res})
}
