// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/prod.proto

/*
	Package example is a generated protocol buffer package.

	It is generated from these files:
		example/prod.proto

	It has these top-level messages:
		Prod
		Sku
		ProdId
		Empty
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golangper/protoc-gen-rorm/options"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// import "github.com/golangper/protoc-gen-rorm/example/user.proto";
type Prod struct {
	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Skus    []*Sku `protobuf:"bytes,4,rep,name=skus" json:"skus,omitempty"`
}

func (m *Prod) Reset()                    { *m = Prod{} }
func (m *Prod) String() string            { return proto.CompactTextString(m) }
func (*Prod) ProtoMessage()               {}
func (*Prod) Descriptor() ([]byte, []int) { return fileDescriptorProd, []int{0} }

func (m *Prod) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Prod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Prod) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Prod) GetSkus() []*Sku {
	if m != nil {
		return m.Skus
	}
	return nil
}

type Sku struct {
	SkuId  int64   `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Price  float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Bn     string  `protobuf:"bytes,3,opt,name=bn,proto3" json:"bn,omitempty"`
	Weight float32 `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	ProdId int64   `protobuf:"varint,5,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
}

func (m *Sku) Reset()                    { *m = Sku{} }
func (m *Sku) String() string            { return proto.CompactTextString(m) }
func (*Sku) ProtoMessage()               {}
func (*Sku) Descriptor() ([]byte, []int) { return fileDescriptorProd, []int{1} }

func (m *Sku) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *Sku) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Sku) GetBn() string {
	if m != nil {
		return m.Bn
	}
	return ""
}

func (m *Sku) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Sku) GetProdId() int64 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

type ProdId struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ProdId) Reset()                    { *m = ProdId{} }
func (m *ProdId) String() string            { return proto.CompactTextString(m) }
func (*ProdId) ProtoMessage()               {}
func (*ProdId) Descriptor() ([]byte, []int) { return fileDescriptorProd, []int{2} }

func (m *ProdId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptorProd, []int{3} }

func init() {
	proto.RegisterType((*Prod)(nil), "example.Prod")
	proto.RegisterType((*Sku)(nil), "example.Sku")
	proto.RegisterType((*ProdId)(nil), "example.ProdId")
	proto.RegisterType((*Empty)(nil), "example.empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Product service

type ProductClient interface {
	GetProd(ctx context.Context, in *ProdId, opts ...grpc.CallOption) (*Prod, error)
	SetProd(ctx context.Context, in *Prod, opts ...grpc.CallOption) (*Empty, error)
}

type productClient struct {
	cc *grpc.ClientConn
}

func NewProductClient(cc *grpc.ClientConn) ProductClient {
	return &productClient{cc}
}

func (c *productClient) GetProd(ctx context.Context, in *ProdId, opts ...grpc.CallOption) (*Prod, error) {
	out := new(Prod)
	err := grpc.Invoke(ctx, "/example.product/getProd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) SetProd(ctx context.Context, in *Prod, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/example.product/setProd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductServer interface {
	GetProd(context.Context, *ProdId) (*Prod, error)
	SetProd(context.Context, *Prod) (*Empty, error)
}

func RegisterProductServer(s *grpc.Server, srv ProductServer) {
	s.RegisterService(&_Product_serviceDesc, srv)
}

func _Product_GetProd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProdId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetProd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.product/GetProd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetProd(ctx, req.(*ProdId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_SetProd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).SetProd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.product/SetProd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).SetProd(ctx, req.(*Prod))
	}
	return interceptor(ctx, in, info, handler)
}

var _Product_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getProd",
			Handler:    _Product_GetProd_Handler,
		},
		{
			MethodName: "setProd",
			Handler:    _Product_SetProd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/prod.proto",
}

func (m *Prod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Prod) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProd(dAtA, i, uint64(m.Id))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintProd(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Details) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProd(dAtA, i, uint64(len(m.Details)))
		i += copy(dAtA[i:], m.Details)
	}
	if len(m.Skus) > 0 {
		for _, msg := range m.Skus {
			dAtA[i] = 0x22
			i++
			i = encodeVarintProd(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Sku) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sku) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SkuId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProd(dAtA, i, uint64(m.SkuId))
	}
	if m.Price != 0 {
		dAtA[i] = 0x15
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Price))))
		i += 4
	}
	if len(m.Bn) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProd(dAtA, i, uint64(len(m.Bn)))
		i += copy(dAtA[i:], m.Bn)
	}
	if m.Weight != 0 {
		dAtA[i] = 0x25
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Weight))))
		i += 4
	}
	if m.ProdId != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintProd(dAtA, i, uint64(m.ProdId))
	}
	return i, nil
}

func (m *ProdId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProdId) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProd(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *Empty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Empty) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintProd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Prod) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovProd(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovProd(uint64(l))
	}
	l = len(m.Details)
	if l > 0 {
		n += 1 + l + sovProd(uint64(l))
	}
	if len(m.Skus) > 0 {
		for _, e := range m.Skus {
			l = e.Size()
			n += 1 + l + sovProd(uint64(l))
		}
	}
	return n
}

func (m *Sku) Size() (n int) {
	var l int
	_ = l
	if m.SkuId != 0 {
		n += 1 + sovProd(uint64(m.SkuId))
	}
	if m.Price != 0 {
		n += 5
	}
	l = len(m.Bn)
	if l > 0 {
		n += 1 + l + sovProd(uint64(l))
	}
	if m.Weight != 0 {
		n += 5
	}
	if m.ProdId != 0 {
		n += 1 + sovProd(uint64(m.ProdId))
	}
	return n
}

func (m *ProdId) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovProd(uint64(m.Id))
	}
	return n
}

func (m *Empty) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovProd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProd(x uint64) (n int) {
	return sovProd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Prod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Prod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Prod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skus = append(m.Skus, &Sku{})
			if err := m.Skus[len(m.Skus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sku) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sku: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sku: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkuId", wireType)
			}
			m.SkuId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SkuId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Price = float32(math.Float32frombits(v))
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProd
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Weight = float32(math.Float32frombits(v))
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProdId", wireType)
			}
			m.ProdId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProdId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProdId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProdId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProdId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Empty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: empty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: empty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthProd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProd   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("example/prod.proto", fileDescriptorProd) }

var fileDescriptorProd = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0x36, 0xc9, 0xee, 0xa6, 0x9d, 0xd6, 0x2a, 0x83, 0xd1, 0x98, 0xc3, 0x32, 0xe4, 0xb2, 0x5b,
	0x49, 0x13, 0xac, 0x07, 0xc1, 0x52, 0x16, 0x0a, 0x22, 0xf5, 0x54, 0xb6, 0x57, 0x41, 0x36, 0x3b,
	0xd3, 0x74, 0xdc, 0xdd, 0x99, 0x98, 0x99, 0x69, 0x2b, 0x78, 0xf3, 0x22, 0x05, 0x41, 0x3c, 0x89,
	0xe0, 0xbf, 0x20, 0xfe, 0x19, 0x7a, 0xf3, 0x96, 0xab, 0xd4, 0xbb, 0x7f, 0x83, 0xcc, 0x8f, 0x16,
	0xba, 0x9e, 0xf2, 0xde, 0xcc, 0x7b, 0xdf, 0xfb, 0xbe, 0x6f, 0x5e, 0x00, 0x24, 0x67, 0x93, 0x45,
	0x3d, 0x27, 0x45, 0xdd, 0x70, 0x9c, 0xd7, 0x0d, 0x97, 0x1c, 0x86, 0xee, 0x2c, 0x79, 0x5c, 0x51,
	0x79, 0xac, 0xca, 0x7c, 0xca, 0x17, 0x45, 0xc5, 0xe7, 0x13, 0x56, 0xd5, 0xa4, 0x29, 0x4c, 0xd1,
	0x74, 0xab, 0x22, 0x6c, 0xab, 0xe1, 0xcd, 0xa2, 0xe0, 0xb5, 0xa4, 0x9c, 0x89, 0x42, 0x27, 0x16,
	0x21, 0x3d, 0x02, 0x9d, 0x83, 0x86, 0x63, 0xb8, 0x01, 0x7c, 0x8a, 0x63, 0x0f, 0x79, 0xc3, 0x60,
	0xec, 0x53, 0x0c, 0x21, 0xe8, 0xb0, 0xc9, 0x82, 0xc4, 0x3e, 0xf2, 0x86, 0xab, 0x63, 0x13, 0xc3,
	0x18, 0x84, 0x98, 0xc8, 0x09, 0x9d, 0x8b, 0x38, 0x30, 0xc7, 0x97, 0x29, 0x44, 0xa0, 0x23, 0x66,
	0x4a, 0xc4, 0x1d, 0x14, 0x0c, 0xd7, 0xb6, 0xd7, 0x73, 0x47, 0x2b, 0x3f, 0x9c, 0xa9, 0xb1, 0xb9,
	0x49, 0x05, 0x08, 0x0e, 0x67, 0x0a, 0x46, 0xa0, 0x27, 0x66, 0xea, 0xe5, 0xd5, 0xa8, 0xae, 0x98,
	0xa9, 0x7d, 0x0c, 0xef, 0x80, 0x6e, 0xdd, 0xd0, 0xa9, 0x1d, 0xe7, 0x8f, 0x6d, 0xa2, 0x39, 0x95,
	0xcc, 0x8d, 0xf2, 0x4b, 0x06, 0xef, 0x82, 0xde, 0x29, 0xa1, 0xd5, 0xb1, 0x8c, 0x3b, 0xa6, 0xcc,
	0x65, 0xf0, 0x1e, 0x08, 0xb5, 0x27, 0x1a, 0xb5, 0x6b, 0x50, 0x7b, 0x3a, 0xdd, 0xc7, 0x69, 0x0c,
	0x7a, 0x07, 0x26, 0x5a, 0x96, 0x97, 0x86, 0xa0, 0x4b, 0x16, 0xb5, 0x7c, 0xb3, 0xfd, 0xb1, 0x63,
	0x9b, 0xd5, 0x54, 0xc2, 0x9f, 0x1e, 0x08, 0x2b, 0x22, 0x8d, 0x1f, 0xb7, 0xae, 0x34, 0x58, 0x84,
	0xe4, 0xe6, 0xb5, 0x83, 0xf4, 0xab, 0x77, 0xde, 0x46, 0x6f, 0x41, 0xc0, 0x95, 0x84, 0x2b, 0xe2,
	0xf5, 0xfc, 0x2c, 0x7f, 0x46, 0x64, 0x32, 0x18, 0x08, 0x32, 0x27, 0x53, 0x89, 0x1e, 0xa0, 0xa3,
	0x86, 0x2f, 0x90, 0x46, 0x46, 0xa7, 0xc7, 0xa4, 0x21, 0x88, 0x62, 0xb4, 0x8b, 0x46, 0x83, 0x1d,
	0xca, 0x72, 0x8a, 0x9f, 0xec, 0x81, 0x15, 0xae, 0x64, 0xae, 0xad, 0x81, 0x6b, 0xa6, 0xfd, 0xd0,
	0x34, 0x26, 0x9b, 0x4b, 0x08, 0x62, 0xa6, 0x1c, 0x80, 0x93, 0xb8, 0x7b, 0x89, 0xf1, 0xa5, 0x8d,
	0xee, 0x83, 0xa0, 0x22, 0x12, 0xc2, 0xb4, 0x38, 0x79, 0x68, 0xd6, 0xa2, 0x70, 0xf4, 0x53, 0xf8,
	0xcd, 0x07, 0xa1, 0x70, 0x5a, 0xae, 0x53, 0x4f, 0x36, 0xae, 0x52, 0x63, 0x41, 0xfa, 0xce, 0x3f,
	0x6f, 0xa3, 0xbf, 0x5e, 0xfa, 0xc2, 0xaa, 0x59, 0x35, 0x74, 0x9e, 0x9e, 0x91, 0x69, 0xf2, 0x7c,
	0x40, 0x99, 0x20, 0x8d, 0x44, 0x94, 0x49, 0x6e, 0xc5, 0x0c, 0x29, 0xce, 0xf4, 0x32, 0x64, 0xee,
	0xe9, 0x37, 0xd1, 0xc9, 0x64, 0xae, 0x88, 0x40, 0xc3, 0x51, 0x36, 0xca, 0x46, 0x9b, 0x83, 0x1d,
	0x45, 0xb1, 0x26, 0xa8, 0x8b, 0xf4, 0xd7, 0xd5, 0xa5, 0x1f, 0xbc, 0xff, 0xe0, 0x9b, 0x6b, 0xf0,
	0x5a, 0xe9, 0xd0, 0x2e, 0x47, 0x66, 0xde, 0x3f, 0x2b, 0x59, 0x66, 0x5f, 0x38, 0x73, 0xda, 0x97,
	0x86, 0xb9, 0x81, 0xbc, 0x7c, 0x95, 0xdb, 0x3e, 0x13, 0x9a, 0x5e, 0x13, 0x95, 0xcc, 0x7c, 0x2c,
	0x86, 0x35, 0x2d, 0x0d, 0x29, 0x33, 0xae, 0x7f, 0x6a, 0xa3, 0x75, 0x10, 0x28, 0x8a, 0x61, 0xd7,
	0x5c, 0x24, 0x2b, 0xef, 0xdb, 0xc8, 0xfb, 0xde, 0x46, 0xde, 0xde, 0xed, 0x1f, 0x17, 0x7d, 0xef,
	0xd7, 0x45, 0xdf, 0xfb, 0x7d, 0xd1, 0xf7, 0x3e, 0xff, 0xe9, 0xdf, 0x28, 0x7b, 0xe6, 0x5f, 0x79,
	0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x28, 0x7a, 0xa2, 0x83, 0x03, 0x00, 0x00,
}
