// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rorm.proto

/*
Package options is a generated protocol buffer package.

It is generated from these files:
	rorm.proto

It has these top-level messages:
	ApiConfig
	RormApi
	RormOptions
	MzsetOptions
	TranOptions
	UidOptions
	Variable
*/
package options

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ApiConfig struct {
	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Provide string `protobuf:"bytes,2,opt,name=provide,proto3" json:"provide,omitempty"`
}

func (m *ApiConfig) Reset()                    { *m = ApiConfig{} }
func (m *ApiConfig) String() string            { return proto.CompactTextString(m) }
func (*ApiConfig) ProtoMessage()               {}
func (*ApiConfig) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{0} }

func (m *ApiConfig) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ApiConfig) GetProvide() string {
	if m != nil {
		return m.Provide
	}
	return ""
}

type RormApi struct {
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (m *RormApi) Reset()                    { *m = RormApi{} }
func (m *RormApi) String() string            { return proto.CompactTextString(m) }
func (*RormApi) ProtoMessage()               {}
func (*RormApi) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{1} }

func (m *RormApi) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RormApi) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RormOptions struct {
	Target   string         `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Method   string         `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Param    string         `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	SqlxTran []*TranOptions `protobuf:"bytes,4,rep,name=sqlx_tran,json=sqlxTran" json:"sqlx_tran,omitempty"`
	Mzset    *MzsetOptions  `protobuf:"bytes,5,opt,name=mzset" json:"mzset,omitempty"`
	Success  *RormOptions   `protobuf:"bytes,7,opt,name=success" json:"success,omitempty"`
	Failure  *RormOptions   `protobuf:"bytes,8,opt,name=failure" json:"failure,omitempty"`
	Slice    string         `protobuf:"bytes,9,opt,name=slice,proto3" json:"slice,omitempty"`
}

func (m *RormOptions) Reset()                    { *m = RormOptions{} }
func (m *RormOptions) String() string            { return proto.CompactTextString(m) }
func (*RormOptions) ProtoMessage()               {}
func (*RormOptions) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{2} }

func (m *RormOptions) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RormOptions) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RormOptions) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *RormOptions) GetSqlxTran() []*TranOptions {
	if m != nil {
		return m.SqlxTran
	}
	return nil
}

func (m *RormOptions) GetMzset() *MzsetOptions {
	if m != nil {
		return m.Mzset
	}
	return nil
}

func (m *RormOptions) GetSuccess() *RormOptions {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *RormOptions) GetFailure() *RormOptions {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *RormOptions) GetSlice() string {
	if m != nil {
		return m.Slice
	}
	return ""
}

type MzsetOptions struct {
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Field  string `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	Value  string `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MzsetOptions) Reset()                    { *m = MzsetOptions{} }
func (m *MzsetOptions) String() string            { return proto.CompactTextString(m) }
func (*MzsetOptions) ProtoMessage()               {}
func (*MzsetOptions) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{3} }

func (m *MzsetOptions) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *MzsetOptions) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *MzsetOptions) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MzsetOptions) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *MzsetOptions) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TranOptions struct {
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Param  string `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	Slice  string `protobuf:"bytes,4,opt,name=slice,proto3" json:"slice,omitempty"`
}

func (m *TranOptions) Reset()                    { *m = TranOptions{} }
func (m *TranOptions) String() string            { return proto.CompactTextString(m) }
func (*TranOptions) ProtoMessage()               {}
func (*TranOptions) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{4} }

func (m *TranOptions) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *TranOptions) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TranOptions) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *TranOptions) GetSlice() string {
	if m != nil {
		return m.Slice
	}
	return ""
}

type UidOptions struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Seed string `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (m *UidOptions) Reset()                    { *m = UidOptions{} }
func (m *UidOptions) String() string            { return proto.CompactTextString(m) }
func (*UidOptions) ProtoMessage()               {}
func (*UidOptions) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{5} }

func (m *UidOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UidOptions) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

type Variable struct {
	VarName string `protobuf:"bytes,1,opt,name=varName,proto3" json:"varName,omitempty"`
	VarType string `protobuf:"bytes,2,opt,name=varType,proto3" json:"varType,omitempty"`
}

func (m *Variable) Reset()                    { *m = Variable{} }
func (m *Variable) String() string            { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()               {}
func (*Variable) Descriptor() ([]byte, []int) { return fileDescriptorRorm, []int{6} }

func (m *Variable) GetVarName() string {
	if m != nil {
		return m.VarName
	}
	return ""
}

func (m *Variable) GetVarType() string {
	if m != nil {
		return m.VarType
	}
	return ""
}

var E_XormType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         44401,
	Name:          "rorm.xorm_type",
	Tag:           "varint,44401,opt,name=xorm_type,json=xormType",
	Filename:      "rorm.proto",
}

var E_RedisType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         44402,
	Name:          "rorm.redis_type",
	Tag:           "varint,44402,opt,name=redis_type,json=redisType",
	Filename:      "rorm.proto",
}

var E_UseNsq = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         44403,
	Name:          "rorm.useNsq",
	Tag:           "varint,44403,opt,name=useNsq",
	Filename:      "rorm.proto",
}

var E_GinHandler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         44406,
	Name:          "rorm.gin_handler",
	Tag:           "varint,44406,opt,name=gin_handler,json=ginHandler",
	Filename:      "rorm.proto",
}

var E_GrpcApiImp = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         44407,
	Name:          "rorm.grpc_api_imp",
	Tag:           "varint,44407,opt,name=grpc_api_imp,json=grpcApiImp",
	Filename:      "rorm.proto",
}

var E_ApiCfg = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*ApiConfig)(nil),
	Field:         44408,
	Name:          "rorm.api_cfg",
	Tag:           "bytes,44408,opt,name=api_cfg,json=apiCfg",
	Filename:      "rorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*RormOptions)(nil),
	Field:         44401,
	Name:          "rorm.opts",
	Tag:           "bytes,44401,opt,name=opts",
	Filename:      "rorm.proto",
}

var E_Uid = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*UidOptions)(nil),
	Field:         44402,
	Name:          "rorm.uid",
	Tag:           "bytes,44402,opt,name=uid",
	Filename:      "rorm.proto",
}

var E_Api = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*RormApi)(nil),
	Field:         44403,
	Name:          "rorm.api",
	Tag:           "bytes,44403,opt,name=api",
	Filename:      "rorm.proto",
}

func init() {
	proto.RegisterType((*ApiConfig)(nil), "rorm.ApiConfig")
	proto.RegisterType((*RormApi)(nil), "rorm.RormApi")
	proto.RegisterType((*RormOptions)(nil), "rorm.RormOptions")
	proto.RegisterType((*MzsetOptions)(nil), "rorm.MzsetOptions")
	proto.RegisterType((*TranOptions)(nil), "rorm.TranOptions")
	proto.RegisterType((*UidOptions)(nil), "rorm.UidOptions")
	proto.RegisterType((*Variable)(nil), "rorm.Variable")
	proto.RegisterExtension(E_XormType)
	proto.RegisterExtension(E_RedisType)
	proto.RegisterExtension(E_UseNsq)
	proto.RegisterExtension(E_GinHandler)
	proto.RegisterExtension(E_GrpcApiImp)
	proto.RegisterExtension(E_ApiCfg)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Uid)
	proto.RegisterExtension(E_Api)
}

func init() { proto.RegisterFile("rorm.proto", fileDescriptorRorm) }

var fileDescriptorRorm = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x6b, 0xd4, 0x4c,
	0x14, 0xc6, 0x69, 0x93, 0x6e, 0x36, 0x27, 0x7d, 0x79, 0xeb, 0x20, 0x12, 0xbc, 0xd0, 0x25, 0x57,
	0x0b, 0x42, 0x0a, 0x55, 0x11, 0x73, 0x51, 0xdc, 0x56, 0x50, 0x91, 0x56, 0x88, 0xd5, 0x0b, 0x6f,
	0x96, 0x69, 0x32, 0x49, 0x07, 0x93, 0xcc, 0x74, 0x26, 0x59, 0x5a, 0xf1, 0xab, 0xf8, 0xc5, 0xfc,
	0x16, 0xb6, 0xa0, 0x5e, 0xca, 0xfc, 0xc9, 0x76, 0x8b, 0x4a, 0x14, 0xbc, 0x3b, 0xcf, 0xd9, 0xe7,
	0xf7, 0xcc, 0x9c, 0xc9, 0xcc, 0x02, 0x08, 0x26, 0xea, 0x98, 0x0b, 0xd6, 0x32, 0xe4, 0xaa, 0xfa,
	0xf6, 0xa4, 0x64, 0xac, 0xac, 0xc8, 0xb6, 0xee, 0x1d, 0x77, 0xc5, 0x76, 0x4e, 0x64, 0x26, 0x28,
	0x6f, 0x99, 0x30, 0xbe, 0xe8, 0x11, 0xf8, 0x33, 0x4e, 0xf7, 0x59, 0x53, 0xd0, 0x12, 0x6d, 0x81,
	0xd3, 0x89, 0x2a, 0x5c, 0x9b, 0xac, 0x4d, 0xfd, 0x54, 0x95, 0x28, 0x04, 0x8f, 0x0b, 0xb6, 0xa0,
	0x39, 0x09, 0xd7, 0x75, 0xb7, 0x97, 0xd1, 0x43, 0xf0, 0x52, 0x26, 0xea, 0x19, 0xa7, 0xe8, 0x16,
	0x8c, 0x6a, 0xd2, 0x9e, 0xb0, 0xdc, 0x92, 0x56, 0x21, 0x04, 0x2e, 0xc7, 0xed, 0x89, 0x25, 0x75,
	0x1d, 0x7d, 0x5a, 0x87, 0x40, 0x71, 0xaf, 0x78, 0x4b, 0x59, 0x23, 0x15, 0xdb, 0x62, 0x51, 0x92,
	0xb6, 0x67, 0x8d, 0x5a, 0xc9, 0x5c, 0xbf, 0x96, 0x79, 0x13, 0x36, 0x38, 0x16, 0xb8, 0x0e, 0x1d,
	0xdd, 0x36, 0x02, 0xc5, 0xe0, 0xcb, 0xd3, 0xea, 0x6c, 0xde, 0x0a, 0xdc, 0x84, 0xee, 0xc4, 0x99,
	0x06, 0x3b, 0x37, 0x62, 0x7d, 0x1a, 0x47, 0x02, 0x37, 0x76, 0xad, 0x74, 0xac, 0x3c, 0xaa, 0x81,
	0xa6, 0xb0, 0x51, 0x7f, 0x90, 0xa4, 0x0d, 0x37, 0x26, 0x6b, 0xd3, 0x60, 0x07, 0x19, 0xef, 0x81,
	0x6a, 0xf5, 0x66, 0x63, 0x40, 0xf7, 0xc0, 0x93, 0x5d, 0x96, 0x11, 0x29, 0x43, 0x4f, 0x7b, 0x6d,
	0xee, 0xca, 0x0c, 0x69, 0xef, 0x50, 0xe6, 0x02, 0xd3, 0xaa, 0x13, 0x24, 0x1c, 0xff, 0xd6, 0x6c,
	0x1d, 0x6a, 0x12, 0x59, 0xd1, 0x8c, 0x84, 0xbe, 0x99, 0x44, 0x8b, 0xe8, 0x23, 0x6c, 0xae, 0x6e,
	0xe3, 0xaf, 0xcf, 0x67, 0x0b, 0x9c, 0xf7, 0xe4, 0xdc, 0x9e, 0x8e, 0x2a, 0xd5, 0x3a, 0x05, 0x25,
	0x55, 0xae, 0x67, 0xf5, 0x53, 0x23, 0x54, 0x77, 0x81, 0xab, 0x8e, 0x84, 0x23, 0xd3, 0xd5, 0x22,
	0xa2, 0x10, 0xac, 0x1c, 0xd8, 0x3f, 0xfa, 0x38, 0xcb, 0x41, 0xdd, 0xd5, 0x41, 0x1f, 0x00, 0xbc,
	0xa1, 0x79, 0xbf, 0x12, 0x02, 0xb7, 0xc1, 0x35, 0xb1, 0xeb, 0xe8, 0x5a, 0xf5, 0x24, 0x21, 0xfd,
	0x1a, 0xba, 0x8e, 0x76, 0x61, 0xfc, 0x16, 0x0b, 0x8a, 0x8f, 0x2b, 0xa2, 0xee, 0xe6, 0x02, 0x8b,
	0xc3, 0x2b, 0xac, 0x97, 0xf6, 0x97, 0xa3, 0x73, 0xbe, 0xbc, 0xb5, 0x56, 0x26, 0xbb, 0xe0, 0x9f,
	0x31, 0x51, 0xcf, 0xdb, 0x73, 0x4e, 0xd0, 0xdd, 0xd8, 0x3c, 0x8f, 0xb8, 0x7f, 0x1e, 0xf1, 0x6b,
	0x22, 0x16, 0x34, 0x23, 0x76, 0x57, 0xe1, 0x97, 0xcf, 0x0a, 0x77, 0xd2, 0xb1, 0x62, 0x34, 0xff,
	0x04, 0x40, 0x90, 0x9c, 0xca, 0x3f, 0x0c, 0xb8, 0xb0, 0x01, 0xbe, 0x86, 0x74, 0xc2, 0x63, 0x18,
	0x75, 0x92, 0x1c, 0xca, 0xd3, 0x61, 0xfa, 0x52, 0xd3, 0xe3, 0xd4, 0x02, 0xc9, 0x1e, 0x04, 0x25,
	0x6d, 0xe6, 0x27, 0xb8, 0xc9, 0x2b, 0x22, 0x86, 0xf9, 0xaf, 0x96, 0x87, 0x92, 0x36, 0xcf, 0x0d,
	0x94, 0xec, 0xc3, 0x66, 0x29, 0x78, 0x36, 0xc7, 0x9c, 0xce, 0x69, 0xcd, 0x87, 0x43, 0xbe, 0x2d,
	0x43, 0x04, 0xcf, 0x66, 0x9c, 0xbe, 0xa8, 0x79, 0xf2, 0x12, 0x3c, 0xc5, 0x67, 0x45, 0x39, 0xcc,
	0x7f, 0xd7, 0x7c, 0xb0, 0xf3, 0xbf, 0x79, 0x0a, 0xcb, 0x3f, 0x9b, 0x74, 0x84, 0x39, 0xdd, 0x2f,
	0xca, 0xe4, 0x19, 0xb8, 0x8c, 0xb7, 0x12, 0xdd, 0xf9, 0x29, 0xe9, 0x40, 0xdf, 0xaa, 0xeb, 0x1f,
	0xe3, 0x97, 0x6f, 0x4a, 0x07, 0x24, 0x4f, 0xc1, 0xe9, 0x68, 0x3e, 0x98, 0x73, 0x61, 0x73, 0xb6,
	0x4c, 0xce, 0xd5, 0x25, 0x4c, 0x15, 0x9e, 0xcc, 0xc0, 0xc1, 0x9c, 0x0e, 0xa6, 0x5c, 0xda, 0x94,
	0xff, 0xae, 0x76, 0x33, 0xe3, 0x34, 0x55, 0xec, 0x9e, 0xff, 0xce, 0x63, 0xc6, 0x76, 0x3c, 0xd2,
	0xf8, 0xfd, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x91, 0xbd, 0x4f, 0x9b, 0x05, 0x00, 0x00,
}
